services:
  swagger-ui:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./docs:/usr/share/nginx/html

  app:
    build: ./app
    ports:
      - 8095:80
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./app:/code/app

  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
